name: rempah_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  intl: ^0.18.1
  http: ^1.1.0
  envied: ^0.3.0+3
  marquee_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
   - assets/
